### ISSUE TITLE
something broken

### ISSUE THREAD

**Issue by eMPee584** [sanskritbscs/memory#3]
![Screenshot_20201213-161001](https://user-images.githubusercontent.com/1227833/102015777-d6354400-3d5d-11eb-946f-b66f43e63e58.png)
but an open source nagri app is a great idea, don't get discouraged by the usual Android platform issues.. 😅

**Comment by sanskritbscs** [comment]
Thank you for reporting.
Seems like they broke webview under android 11.
Need some time to figure it out.

**Comment by sanskritbscs** [comment]
fixed in aa6f81725b53168c8fc0354b7c5d69866299dee4
Thanks.
