### ISSUE TITLE
Blue screen bug - Web page not available

### ISSUE THREAD

**Issue by gaellafond** [sanskritbscs/memory#4]
The latest version (3.0) is unusable. It shows a blue screen on start (see screenshot bellow).
![2020-12-22](https://user-images.githubusercontent.com/936244/102954057-a6c8c900-450d-11eb-9d7c-56354c6f459b.png)

Phone: Nokia 6.2
Android: 10

I tried uninstalling / re-installing the app. I also cleared app data and cache.

I have downgraded to Version 2.9 for now

**Comment by gaellafond** [comment]
Probably a duplicate of issue #3 
Except this one is for Android 10 (I'm not sure if that changes anything)

**Comment by sanskritbscs** [comment]
Hello!
Thank you for reporting.
This should be fixed in 3.1

**Comment by sanskritbscs** [comment]
Please try installing from here [v3.1](https://github.com/sanskritbscs/memory/releases/tag/v3.1)
It will take about a week for a new version to be published in f-droid

**Comment by gaellafond** [comment]
Thanks! I installed version 3.1. That fixed the issue.
