### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [sanskritbscs/memory#5]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the components in the red box are misplaced. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 3.0, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="473" alt="bug-memory_25" src="https://user-images.githubusercontent.com/18572115/103228038-dabb4880-496a-11eb-94fc-2e2b642046f2.png">

**Comment by sanskritbscs** [comment]
I am truly grateful for your report.
This issue should be fixed in "3.2" release available [here](https://github.com/sanskritbscs/memory/releases/tag/v3.2) and will be available at f-droid not very soon.
Signature is different, so you would have to uninstall first.

Thank you.

**Comment by franklinbill** [comment]
Thanks*100000 for your reply! The bug has been fixed and can be displayed normally.
